# Windows
# NET stop HTTP
# docker network create proxy
version: '3.7'
services:
  traefik:
    image: traefik:v2.4
    ports:
      - 80:80
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./traefik.yaml:/traefik.yaml
      - ./routes.yaml:/routes.yaml:rw
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.tf.rule=Host(`tf.home.lan`)"
      - "traefik.http.routers.tf.service=api@internal"
    environment:
      - TZ=Asia/Bangkok
    networks:
      - proxy
networks:
  proxy:
    external: true
