# modify from https://tech.aufomm.com/deploy-wordpress-with-docker-and-traefik-2/
version: '3.7'
services:
  db:
    image: mariadb
    container_name: wp-db
    volumes:
      - ./db-data:/var/lib/mysql
    networks:
      - default
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: supersecretpassword
      MYSQL_DATABASE: db
      MYSQL_USER: dbuser
      MYSQL_PASSWORD: dbpassword
  wordpress:
    restart: always
    depends_on:
      - db
    image: wordpress:latest
    container_name: wordpress
    ports:
      - "8082:80"
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_NAME: db
      WORDPRESS_DB_USER: dbuser
      WORDPRESS_DB_PASSWORD: dbpassword
    volumes:
      - ./wp-data:/var/www/html/wp-content

